### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by hafizahmmed** [euri16/tourist-ai#8]
Hello,
Good Day, i make a logo icon for your project. If you want to use this logo in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.It's totally free for open source project.

![tourist-ai-01](https://user-images.githubusercontent.com/38810169/42290136-3f403452-7fe5-11e8-9948-6cd05fa9d237.jpg)

**Comment by euri16** [comment]
This logo looks awesome, the commercial name is "Kahi" by the way.

**Comment by hafizahmmed** [comment]
ok thank you sir. 

can i make a  pull request ??

**Comment by euri16** [comment]
Sure, do it an I will check it out.

**Comment by hafizahmmed** [comment]
![tourist-ai-01](https://user-images.githubusercontent.com/38810169/42314052-f93842c0-8065-11e8-9f30-13890d12b615.jpg)

**Comment by hafizahmmed** [comment]
please check #9

**Comment by euri16** [comment]
Merged!
